# Simpe input system handling input events
# generated by pygame event system.
class Input:
    def __init__(self):
        self.listeners = []

    def addListener(self, listener):
        self.listeners.append(listener)

    def removeListener(self, listener):
        self.listeners.remove(listener)

    def dispatchEvent(self, event):
        for listener in self.listeners:
            consumed = listener.onEvent(event)
            if consumed: return True
        return False